### ISSUE TITLE
PortAudio error

### ISSUE THREAD

**Issue by vonhex** [dnhkng/GlaDOS#14]
Ive gotten this on WSL, Linux, and PI OS Bookworm

(env) admin@ai:~/GlaDOS $ python glados.py
Traceback (most recent call last):
  File "/home/admin/GlaDOS/glados.py", line 14, in <module>
    import sounddevice as sd
  File "/home/admin/GlaDOS/env/lib/python3.11/site-packages/sounddevice.py", line 71, in <module>
    raise OSError('PortAudio library not found')
OSError: PortAudio library not found

**Comment by vonhex** [comment]
fixed by installing 

sudo apt-get install libportaudio2
