### ISSUE TITLE
AttributeError: 'ASR' object has no attribute 'ctx'

### ISSUE THREAD

**Issue by Hayate72** [dnhkng/GlaDOS#30]
Hello,

I'm block when I tried to launch the script. This is the message : 

> 2024-05-08 21:51:50.1156801 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '620'. It is not used by any node and should be removed from the model.
2024-05-08 21:51:50.1194426 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '623'. It is not used by any node and should be removed from the model.
2024-05-08 21:51:50.1233524 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '625'. It is not used by any node and should be removed from the model.
2024-05-08 21:51:50.1269919 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '629'. It is not used by any node and should be removed from the model.
2024-05-08 21:51:50.1320727 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '628'. It is not used by any node and should be removed from the model.
2024-05-08 21:51:50.1362505 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '131'. It is not used by any node and should be removed from the model.
2024-05-08 21:51:50.1402363 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '134'. It is not used by any node and should be removed from the model.
2024-05-08 21:51:50.1440089 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '136'. It is not used by any node and should be removed from the model.
2024-05-08 21:51:50.1484948 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '140'. It is not used by any node and should be removed from the model.
2024-05-08 21:51:50.1522116 [W:onnxruntime:, graph.cc:3593 onnxruntime::Graph::CleanUnusedInitializersAndNodeArgs] Removing initializer '139'. It is not used by any node and should be removed from the model.
Traceback (most recent call last):
  File "D:\Dev\GlaDOS\glados.py", line 555, in <module>
    glados = Glados.from_config(glados_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dev\GlaDOS\glados.py", line 166, in from_config
    return cls(
           ^^^^
  File "D:\Dev\GlaDOS\glados.py", line 102, in __init__
    self._asr_model = asr.ASR(model=str(Path.cwd() / "models" / ASR_MODEL))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dev\GlaDOS\glados\asr.py", line 23, in __init__
    self.ctx = whisper_cpp_wrapper.whisper_init_from_file(model.encode("utf-8"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'glados.whisper_cpp_wrapper' has no attribute 'whisper_init_from_file'
Exception ignored in: <function ASR.__del__ at 0x000001FAFFBF3D80>
Traceback (most recent call last):
  File "D:\Dev\GlaDOS\glados\asr.py", line 61, in __del__
    whisper_cpp_wrapper.whisper_free(self.ctx)
                                     ^^^^^^^^
AttributeError: 'ASR' object has no attribute 'ctx'

Please help me...

**Comment by dnhkng** [comment]
Looks like you are on Windows.  New code for that platiis being developed, should be ready soon I hope.

**Comment by Hayate72** [comment]
Yes, I forgot to tell, I'm on Windows. I will test on Linux in that case. Thanks for your quick reply.

**Comment by dnhkng** [comment]
There is now a windows branch in testing. There is a batch file that *sometimes* works.

If not, try the commands from in the batch file one at a time.
