### ISSUE TITLE
whisper error

### ISSUE THREAD

**Issue by nabeelshaikh7** [dnhkng/GlaDOS#34]
I have downloaded whisper and kept it in the folder but it still gives me this error

``` Traceback (most recent call last):
File "/home/nabeel/GlaD0OS/glados.py", line 21, in <module>
from glados import asr, tts, vad
File "/home/nabeel/GlaDOS/glados/asr.py", line 5, in <module>
from . import whisper_cpp_wrapper
File "/home/nabeel/GlaDOS/glados/whisper_cpp_wrapper.py", line 861, in <module
>
_libs["whisper"] = load_library("whisper")
AAAAAAANAANANANANANAANANANAANAAAAN
File "/home/nabeel/GlaD0S/glados/whisper_cpp_wrapper.py", line 547, in __call_
" raise ImportError("Could not load %s." % libname)
ImportError: Could not load whisper.
- - ~ Y e e ~1 A 23 P |```

**Comment by dnhkng** [comment]
Yep. Make generates Libwhisper.so which must be in the GLaDOS/submodules/whisper.cpp directory, or you get this error.
