### ISSUE TITLE
Error running on windows

### ISSUE THREAD

**Issue by Ghostboo124** [dnhkng/GlaDOS#52]
Hello,
I am having an issue running start_windows.bat, i have tried rerunning intall_windows.bat, but i am still getting the error, I have also tried manually installing whisper through
Traceback (most recent call last):
  File "D:\GLaDOS\GlaDOS\glados.py", line 21, in <module>
    from glados import asr, tts, vad
  File "D:\GLaDOS\GlaDOS\glados\asr.py", line 5, in <module>
    from . import whisper_cpp_wrapper
  File "D:\GLaDOS\GlaDOS\glados\whisper_cpp_wrapper.py", line 861, in <module>
    _libs["whisper"] = load_library("whisper")
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GLaDOS\GlaDOS\glados\whisper_cpp_wrapper.py", line 547, in __call__
    raise ImportError("Could not load %s." % libname)
ImportError: Could not load whisper.

**Comment by dnhkng** [comment]
Ask in here, and check the FAQ:
https://discord.com/invite/2K3HaW7N
