### ISSUE TITLE
Some Windows Troubles (Win 10)

### ISSUE THREAD

**Issue by cushycrux** [dnhkng/GlaDOS#68]
Hi there, I have some problems, maybe some can help.

1. The Windows Installer Bat does not work with Python 3.10, - i changed it to call "python" not "python3.12", so the installer is somehow working. Not automatic but manual, the bat does not open the setup and or open venv correctly. so opening a console as admin and copy line by line from the bat worked fine. - Everything Istalled.
2. the readme says "To use Python 3.10, install `typing_extensions` and replace `import typing` in `glados/llama.py` with `import typing_extensions`." - But there is no "import typing" at all in that file. so is this alteration correct?

```
import subprocess
import time
import typing_extensions
from dataclasses import dataclass
from pathlib import Path
from typing_extensions import Self, Sequence
```
3. When running, it stops with:
```
F:\GlaDOS-main>call .\venv\Scripts\activate

(venv) F:\GlaDOS-main>python glados.py
2024-06-30 10:00:52.075 | SUCCESS  | glados.llama:__init__:86 - Command to start the server: [WindowsPath('F:/GlaDOS-main/submodules/llama.cpp/llama-server'), '--model', WindowsPath('F:/GlaDOS-main/models/Meta-Llama-3-8B-Instruct-Q6_K.gguf'), '--ctx-size', '8192', '--port', '8080', '--n-gpu-layers', '1000']
2024-06-30 10:00:52.076 | INFO     | glados.llama:start:117 - Starting the server by executing command self.command=[WindowsPath('F:/GlaDOS-main/submodules/llama.cpp/llama-server'), '--model', WindowsPath('F:/GlaDOS-main/models/Meta-Llama-3-8B-Instruct-Q6_K.gguf'), '--ctx-size', '8192', '--port', '8080', '--n-gpu-layers', '1000']
Traceback (most recent call last):
  File "F:\GlaDOS-main\glados.py", line 604, in <module>
    start()
  File "F:\GlaDOS-main\glados.py", line 583, in start
    llama_server.start()
  File "F:\GlaDOS-main\glados\llama.py", line 118, in start
    self.process = subprocess.Popen(
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

(venv) F:\GlaDOS-main>
```
I am not a coder and did not find a solution to fix the error, so "Whelp please!"

**Comment by dnhkng** [comment]
Just to check: Did you follow the "New Simplified Windows Installation Process", and install Python 3.12 using the Microsoft Store?

It looks like the llama version was not up-to-date. I have just fixed the issue, but it would be great if you could test the update!

**Comment by cushycrux** [comment]
Hi, thanks a lot for answering

Yes I read the instructions, tho I did not install 3.12. As you can see I use 3.10. The problem seems to be the "typing-extensions" part (2.). Can you give me a tip? See here:

When runnning without changeching entrys in glados/llama.py i get:

```
F:\GlaDOS-main>start_windows.bat
Traceback (most recent call last):
  File "F:\GlaDOS-main\glados.py", line 22, in <module>
    from glados.llama import LlamaServer, LlamaServerConfig
  File "F:\GlaDOS-main\glados\llama.py", line 5, in <module>
    from typing import Self, Sequence
ImportError: cannot import name 'Self' from 'typing' (C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\typing.py)
```

After making these changes to llama.py:

`from typing_extensions import Self, Sequence` as told in the readme I get:

```
(venv) F:\GlaDOS-main>pip install typing-extensions
Requirement already satisfied: typing-extensions in f:\glados-main\venv\lib\site-packages (4.12.2)

[notice] A new release of pip available: 22.3.1 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(venv) F:\GlaDOS-main>start_windows.bat
2024-06-30 15:31:48.963 | SUCCESS  | glados.llama:__init__:85 - Command to start the server: [WindowsPath('F:/GlaDOS-main/submodules/llama.cpp/llama-server'), '--model', WindowsPath('F:/GlaDOS-main/models/Meta-Llama-3-8B-Instruct-Q6_K.gguf'), '--ctx-size', '8192', '--port', '8080', '--n-gpu-layers', '1000']
2024-06-30 15:31:48.964 | INFO     | glados.llama:start:116 - Starting the server by executing command self.command=[WindowsPath('F:/GlaDOS-main/submodules/llama.cpp/llama-server'), '--model', WindowsPath('F:/GlaDOS-main/models/Meta-Llama-3-8B-Instruct-Q6_K.gguf'), '--ctx-size', '8192', '--port', '8080', '--n-gpu-layers', '1000']
Traceback (most recent call last):
  File "F:\GlaDOS-main\glados.py", line 604, in <module>
    start()
  File "F:\GlaDOS-main\glados.py", line 583, in start
    llama_server.start()
  File "F:\GlaDOS-main\glados\llama.py", line 117, in start
    self.process = subprocess.Popen(
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```
Thanks again for helping.

**Comment by dnhkng** [comment]
I would first just try installing Python 3.12 too. It doesn't hurt to have multiple versions of python on windows.

Then check in the submodules/llama.cpp folder, and make sure the LlamaServer executable is present. That's what the error is complaining about.

**Comment by cushycrux** [comment]
nope, surly i am seconds bevore a complete destaster. LOL

```
F:\>cd GlaDOS-main

F:\GlaDOS-main>call .\venv\Scripts\activate

(venv) F:\GlaDOS-main>python glados.py
Traceback (most recent call last):
  File "F:\GlaDOS-main\glados.py", line 22, in <module>
    from glados.llama import LlamaServer, LlamaServerConfig
  File "F:\GlaDOS-main\glados\llama.py", line 5, in <module>
    from typing import Self, Sequence
ImportError: cannot import name 'Self' from 'typing' (C:\Users\Dave\AppData\Local\Programs\Python\Python310\lib\typing.py)

(venv) F:\GlaDOS-main>python3.12 glados.py
Der Befehl "python3.12" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

(venv) F:\GlaDOS-main>C:\Users\Dave\AppData\Local\Programs\Python\Python312\python glados.py
Traceback (most recent call last):
  File "F:\GlaDOS-main\glados.py", line 12, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
Instructions unclear, computer is bruning now. How do I switch between these pythons?

**Comment by dnhkng** [comment]
Deep breath, calm....

now that you have python 3.12 installed, probably the best bet is to just delete the glados folder, and download it again.
Then, just run the installer.

Let me know how it goes!

**Comment by cushycrux** [comment]
Uff...loaded restore point. installed 3.12. deleted the installation of glados. restarted your installer after renaming python.exe to python3.12.exe. renamed the python call in windows_start.bat to python3.12 Now it crashes like:

```
2024-06-30 18:59:05.402 | SUCCESS  | glados.llama:__init__:85 - Command to start the server: [WindowsPath('F:/GlaDOS-main/submodules/llama.cpp/llama-server'), '--model', WindowsPath('F:/GlaDOS-main/models/Meta-Llama-3-8B-Instruct-Q6_K.gguf'), '--ctx-size', '8192', '--port', '8080', '--n-gpu-layers', '1000']
2024-06-30 18:59:05.402 | INFO     | glados.llama:start:116 - Starting the server by executing command self.command=[WindowsPath('F:/GlaDOS-main/submodules/llama.cpp/llama-server'), '--model', WindowsPath('F:/GlaDOS-main/models/Meta-Llama-3-8B-Instruct-Q6_K.gguf'), '--ctx-size', '8192', '--port', '8080', '--n-gpu-layers', '1000']
2024-06-30 18:59:18.094 | INFO     | glados.asr:_unlog:25 - whisper_init_from_file_with_params_no_state: loading model from 'F:\GlaDOS-main\models\ggml-medium-32-2.en.bin'
2024-06-30 18:59:18.094 | INFO     | glados.asr:_unlog:25 - whisper_init_with_params_no_state: use gpu    = 1
2024-06-30 18:59:18.095 | INFO     | glados.asr:_unlog:25 - whisper_init_with_params_no_state: flash attn = 0
2024-06-30 18:59:18.095 | INFO     | glados.asr:_unlog:25 - whisper_init_with_params_no_state: gpu_device = 0
2024-06-30 18:59:18.095 | INFO     | glados.asr:_unlog:25 - whisper_init_with_params_no_state: dtw        = 0
2024-06-30 18:59:18.095 | INFO     | glados.asr:_unlog:25 - whisper_model_load: loading model
2024-06-30 18:59:18.096 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_vocab       = 51864
2024-06-30 18:59:18.096 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_audio_ctx   = 1500
2024-06-30 18:59:18.096 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_audio_state = 1024
2024-06-30 18:59:18.096 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_audio_head  = 16
2024-06-30 18:59:18.096 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_audio_layer = 24
2024-06-30 18:59:18.096 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_text_ctx    = 448
2024-06-30 18:59:18.097 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_text_state  = 1024
2024-06-30 18:59:18.097 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_text_head   = 16
2024-06-30 18:59:18.097 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_text_layer  = 2
2024-06-30 18:59:18.097 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_mels        = 80
2024-06-30 18:59:18.097 | INFO     | glados.asr:_unlog:25 - whisper_model_load: ftype         = 1
2024-06-30 18:59:18.097 | INFO     | glados.asr:_unlog:25 - whisper_model_load: qntvr         = 0
2024-06-30 18:59:18.098 | INFO     | glados.asr:_unlog:25 - whisper_model_load: type          = 4 (medium)
2024-06-30 18:59:18.127 | INFO     | glados.asr:_unlog:25 - whisper_model_load: adding 1608 extra tokens
2024-06-30 18:59:18.128 | INFO     | glados.asr:_unlog:25 - whisper_model_load: n_langs       = 99
2024-06-30 18:59:18.132 | INFO     | glados.asr:_unlog:25 - whisper_backend_init: using CUDA backend
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3070 Ti, compute capability 8.6, VMM: yes
2024-06-30 18:59:18.246 | INFO     | glados.asr:_unlog:25 - whisper_model_load:    CUDA0 total size =   793.41 MB
2024-06-30 18:59:19.312 | INFO     | glados.asr:_unlog:25 - whisper_model_load: model size    =  793.41 MB
2024-06-30 18:59:19.317 | INFO     | glados.asr:_unlog:25 - whisper_init_state: kv self size  =   12.58 MB
2024-06-30 18:59:19.329 | INFO     | glados.asr:_unlog:25 - whisper_init_state: kv cross size =   12.58 MB
2024-06-30 18:59:19.330 | INFO     | glados.asr:_unlog:25 - whisper_init_state: kv pad  size  =    6.29 MB
2024-06-30 18:59:19.331 | INFO     | glados.asr:_unlog:25 - whisper_init_state: compute buffer (conv)   =   28.68 MB
2024-06-30 18:59:19.337 | INFO     | glados.asr:_unlog:25 - whisper_init_state: compute buffer (encode) =  594.22 MB
2024-06-30 18:59:19.338 | INFO     | glados.asr:_unlog:25 - whisper_init_state: compute buffer (cross)  =    7.85 MB
2024-06-30 18:59:19.339 | INFO     | glados.asr:_unlog:25 - whisper_init_state: compute buffer (decode) =   98.31 MB
2024-06-30 18:59:22.271 | SUCCESS  | __main__:__init__:151 - TTS text: All neural network modules are now loaded. No network access detected. How very annoying. System Operational.
Traceback (most recent call last):
  File "F:\GlaDOS-main\glados.py", line 604, in <module>
    start()
  File "F:\GlaDOS-main\glados.py", line 599, in start
    glados = Glados.from_config(glados_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GlaDOS-main\glados.py", line 186, in from_config
    return cls(
           ^^^^
  File "F:\GlaDOS-main\glados.py", line 152, in __init__
    self.play_sound(audio, tts.RATE)
                           ^^^^^^^^
AttributeError: module 'glados.tts' has no attribute 'RATE'
```

Thanks again, you must have nerves made out of steel.

**Comment by dnhkng** [comment]
Cool, you found a proper bug! I'll fix it asap!

**Comment by cushycrux** [comment]
Hey, glad to help Dave. Und Grüsse aus der Schweiz.
The Idea of this repo is funny and also pretty hi-end progression stuff. Maybe I can mod it to emulate LCARS or something. :)
Looking forward to test this technical beast.

**Comment by dnhkng** [comment]
Can you download the repo again?  Let me know if the changes fixed the issue.

**Comment by cushycrux** [comment]
sure..give me sec.

**Comment by cushycrux** [comment]
IT WORKS! LOL. Sure i have the interruptin and loop problem, but hey, - thats not your problem right. This is so cool! Thanks again!

**Comment by cushycrux** [comment]
ok, but i crashed now after 5 minutes...
 with:

```
Exception in thread Thread-1 (process_LLM):
Traceback (most recent call last):
  File "F:\GlaDOS-main\venv\Lib\site-packages\urllib3\response.py", line 748, in _error_catcher
    yield
  File "F:\GlaDOS-main\venv\Lib\site-packages\urllib3\response.py", line 1206, in read_chunked
    self._update_chunk_length()
  File "F:\GlaDOS-main\venv\Lib\site-packages\urllib3\response.py", line 1125, in _update_chunk_length
    line = self._fp.fp.readline()  # type: ignore[union-attr]
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\GlaDOS-main\venv\Lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "F:\GlaDOS-main\venv\Lib\site-packages\urllib3\response.py", line 1057, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "F:\GlaDOS-main\venv\Lib\site-packages\urllib3\response.py", line 1189, in read_chunked
    with self._error_catcher():
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(value)
  File "F:\GlaDOS-main\venv\Lib\site-packages\urllib3\response.py", line 775, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None)", ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\Dave\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "F:\GlaDOS-main\glados.py", line 490, in process_LLM
    for line in response.iter_lines():
  File "F:\GlaDOS-main\venv\Lib\site-packages\requests\models.py", line 869, in iter_lines
    for chunk in self.iter_content(
  File "F:\GlaDOS-main\venv\Lib\site-packages\requests\models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None)", ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None))
```
sure glados is playing games with us. ^^

**Comment by dnhkng** [comment]
LOL

There are a few bugs remaining. It's a huge hassle to deal with Mac/Linux/Windows, so now 80% of the work goes into cross platform work, and 20% on making her better 😂

**Comment by cushycrux** [comment]
One thing is sure, you have a fan now. wish you luck and looking forward for new releases ans such...
